//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDAEntities1 : DbContext
    {
        public MDAEntities1()
            : base("name=MDAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<片單總表MovieLists> 片單總表MovieLists { get; set; }
        public virtual DbSet<片種總表TotalTypes> 片種總表TotalTypes { get; set; }
        public virtual DbSet<出售座位明細SeatSold> 出售座位明細SeatSold { get; set; }
        public virtual DbSet<出售座位狀態SeatStatus> 出售座位狀態SeatStatus { get; set; }
        public virtual DbSet<回覆樓數Floor> 回覆樓數Floor { get; set; }
        public virtual DbSet<次片種總表Types> 次片種總表Types { get; set; }
        public virtual DbSet<我的片單MyMovieLists> 我的片單MyMovieLists { get; set; }
        public virtual DbSet<我的追蹤清單MyFollowLists> 我的追蹤清單MyFollowLists { get; set; }
        public virtual DbSet<系列電影MovieSeries> 系列電影MovieSeries { get; set; }
        public virtual DbSet<訂單明細OrderDetail> 訂單明細OrderDetail { get; set; }
        public virtual DbSet<訂單狀態OrderStatus> 訂單狀態OrderStatus { get; set; }
        public virtual DbSet<訂單總表Orders> 訂單總表Orders { get; set; }
        public virtual DbSet<追讚倒ActionTypes> 追讚倒ActionTypes { get; set; }
        public virtual DbSet<商品資料Products> 商品資料Products { get; set; }
        public virtual DbSet<國家總表Countrys> 國家總表Countrys { get; set; }
        public virtual DbSet<票種TicketType> 票種TicketType { get; set; }
        public virtual DbSet<票價資訊TicketPrice> 票價資訊TicketPrice { get; set; }
        public virtual DbSet<場次Screening> 場次Screening { get; set; }
        public virtual DbSet<評論圖片明細CommentImagesList> 評論圖片明細CommentImagesList { get; set; }
        public virtual DbSet<評論圖片總表CommentImages> 評論圖片總表CommentImages { get; set; }
        public virtual DbSet<會員Members> 會員Members { get; set; }
        public virtual DbSet<電影Movies> 電影Movies { get; set; }
        public virtual DbSet<電影分級MovieRating> 電影分級MovieRating { get; set; }
        public virtual DbSet<電影片種MovieType> 電影片種MovieType { get; set; }
        public virtual DbSet<電影主演Cast> 電影主演Cast { get; set; }
        public virtual DbSet<電影代碼MovieCode> 電影代碼MovieCode { get; set; }
        public virtual DbSet<電影院Theater> 電影院Theater { get; set; }
        public virtual DbSet<電影產地MovieOrigin> 電影產地MovieOrigin { get; set; }
        public virtual DbSet<電影評論MovieComment> 電影評論MovieComment { get; set; }
        public virtual DbSet<電影圖片MovieIImagesList> 電影圖片MovieIImagesList { get; set; }
        public virtual DbSet<電影圖片總表MovieImages> 電影圖片總表MovieImages { get; set; }
        public virtual DbSet<電影語言MovieLanguage> 電影語言MovieLanguage { get; set; }
        public virtual DbSet<電影導演MovieDirector> 電影導演MovieDirector { get; set; }
        public virtual DbSet<對象Targets> 對象Targets { get; set; }
        public virtual DbSet<演員總表Actors> 演員總表Actors { get; set; }
        public virtual DbSet<影城MainTheater> 影城MainTheater { get; set; }
        public virtual DbSet<影廳Cinema> 影廳Cinema { get; set; }
        public virtual DbSet<標籤明細HashtagsList> 標籤明細HashtagsList { get; set; }
        public virtual DbSet<標籤總表Hashtags> 標籤總表Hashtags { get; set; }
        public virtual DbSet<導演總表Director> 導演總表Director { get; set; }
        public virtual DbSet<優惠明細CouponLists> 優惠明細CouponLists { get; set; }
        public virtual DbSet<優惠總表Coupon> 優惠總表Coupon { get; set; }
        public virtual DbSet<購買商品明細Receipt> 購買商品明細Receipt { get; set; }
    }
}
