//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 優惠明細CouponLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 優惠明細CouponLists()
        {
            this.訂單總表Orders = new HashSet<訂單總表Orders>();
        }
    
        public int 優惠明細編號CouponList_ID { get; set; }
        public int 會員編號Member_ID { get; set; }
        public int 優惠編號Coupon_ID { get; set; }
        public bool 是否使用優惠OX_CouponUsing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<訂單總表Orders> 訂單總表Orders { get; set; }
        public virtual 會員Members 會員Members { get; set; }
        public virtual 優惠總表Coupon 優惠總表Coupon { get; set; }
    }
}
