//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品資料Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 商品資料Products()
        {
            this.購買商品明細Receipt = new HashSet<購買商品明細Receipt>();
        }
    
        public int 商品編號Product_ID { get; set; }
        public string 商品名稱Product_Name { get; set; }
        public decimal 商品價格Product_Price { get; set; }
        public int 電影院編號Theater_ID { get; set; }
        public byte[] 商品圖片Image { get; set; }
    
        public virtual 電影院Theater 電影院Theater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<購買商品明細Receipt> 購買商品明細Receipt { get; set; }
    }
}
