//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 回覆樓數Floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 回覆樓數Floor()
        {
            this.我的追蹤清單MyFollowLists = new HashSet<我的追蹤清單MyFollowLists>();
        }
    
        public int 樓數編號Floor_ID { get; set; }
        public int 評論編號Comment_ID { get; set; }
        public int 會員編號Member_ID { get; set; }
        public string 回覆內容Floors { get; set; }
        public System.DateTime 發佈時間Floor_Time { get; set; }
        public Nullable<int> 被按讚次數Thumbs_Up { get; set; }
        public Nullable<int> 被倒讚次數Thumbs_Down { get; set; }
        public int 屏蔽Invisible { get; set; }
        public int 檢舉Report { get; set; }
    
        public virtual 電影評論MovieComment 電影評論MovieComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<我的追蹤清單MyFollowLists> 我的追蹤清單MyFollowLists { get; set; }
    }
}
