//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 場次Screening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 場次Screening()
        {
            this.出售座位明細SeatSold = new HashSet<出售座位明細SeatSold>();
            this.出售座位狀態SeatStatus = new HashSet<出售座位狀態SeatStatus>();
            this.訂單總表Orders = new HashSet<訂單總表Orders>();
        }
    
        public int 場次編號Screening_ID { get; set; }
        public int 影廳編號Cinema_ID { get; set; }
        public int 電影代碼Movie_Code { get; set; }
        public System.DateTime 放映日期Play_Date { get; set; }
        public string 放映開始時間Play_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<出售座位明細SeatSold> 出售座位明細SeatSold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<出售座位狀態SeatStatus> 出售座位狀態SeatStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<訂單總表Orders> 訂單總表Orders { get; set; }
        public virtual 電影代碼MovieCode 電影代碼MovieCode { get; set; }
        public virtual 影廳Cinema 影廳Cinema { get; set; }
    }
}
