//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 我的片單MyMovieLists
    {
        public int 我的片單MyMovieList_ID { get; set; }
        public int 片單總表編號MovieList_ID { get; set; }
        public int 會員編號Member_ID { get; set; }
        public int 電影編號Movie_ID { get; set; }
    
        public virtual 片單總表MovieLists 片單總表MovieLists { get; set; }
        public virtual 會員Members 會員Members { get; set; }
        public virtual 電影Movies 電影Movies { get; set; }
    }
}
