//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 標籤明細HashtagsList
    {
        public int 標籤明細編號CH_ID { get; set; }
        public int 評論編號Comment_ID { get; set; }
        public int 標籤編號Hashtag_ID { get; set; }
    
        public virtual 電影評論MovieComment 電影評論MovieComment { get; set; }
        public virtual 標籤總表Hashtags 標籤總表Hashtags { get; set; }
    }
}
