//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 次片種總表Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 次片種總表Types()
        {
            this.電影片種MovieType = new HashSet<電影片種MovieType>();
        }
    
        public int 片種編號TotalType_ID { get; set; }
        public int 次片種編號Type_ID { get; set; }
        public string 次片種名稱Type_Name { get; set; }
    
        public virtual 片種總表TotalTypes 片種總表TotalTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影片種MovieType> 電影片種MovieType { get; set; }
    }
}
