//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 演員總表Actors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 演員總表Actors()
        {
            this.電影主演Cast = new HashSet<電影主演Cast>();
        }
    
        public int 演員編號Actors_ID { get; set; }
        public string 中文名字Name_Cht { get; set; }
        public string 英文名字Name_Eng { get; set; }
        public byte[] 演員照片Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影主演Cast> 電影主演Cast { get; set; }
    }
}
