//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 票價資訊TicketPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 票價資訊TicketPrice()
        {
            this.訂單明細OrderDetail = new HashSet<訂單明細OrderDetail>();
        }
    
        public int 票價明細Ticket_ID { get; set; }
        public int 影城編號MainTheater_ID { get; set; }
        public int 票種編號TicketType_ID { get; set; }
        public decimal 價格TicketPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<訂單明細OrderDetail> 訂單明細OrderDetail { get; set; }
        public virtual 票種TicketType 票種TicketType { get; set; }
        public virtual 影城MainTheater 影城MainTheater { get; set; }
    }
}
