//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單總表Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 訂單總表Orders()
        {
            this.出售座位明細SeatSold = new HashSet<出售座位明細SeatSold>();
            this.訂單明細OrderDetail = new HashSet<訂單明細OrderDetail>();
            this.購買商品明細Receipt = new HashSet<購買商品明細Receipt>();
        }
    
        public int 訂單編號Order_ID { get; set; }
        public int 會員編號Member_ID { get; set; }
        public System.DateTime 訂單時間OrderTime { get; set; }
        public int 場次編號Screening_ID { get; set; }
        public int 優惠明細編號CouponList_ID { get; set; }
        public int 訂單狀態編號OrderStatus_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<出售座位明細SeatSold> 出售座位明細SeatSold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<訂單明細OrderDetail> 訂單明細OrderDetail { get; set; }
        public virtual 訂單狀態OrderStatus 訂單狀態OrderStatus { get; set; }
        public virtual 場次Screening 場次Screening { get; set; }
        public virtual 會員Members 會員Members { get; set; }
        public virtual 優惠明細CouponLists 優惠明細CouponLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<購買商品明細Receipt> 購買商品明細Receipt { get; set; }
    }
}
