//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 評論圖片總表CommentImages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 評論圖片總表CommentImages()
        {
            this.評論圖片明細CommentImagesList = new HashSet<評論圖片明細CommentImagesList>();
        }
    
        public int 評論圖庫編號CommentImage_ID { get; set; }
        public byte[] 圖片Image { get; set; }
        public int 屏蔽Invisible { get; set; }
        public int 檢舉Report { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<評論圖片明細CommentImagesList> 評論圖片明細CommentImagesList { get; set; }
    }
}
