//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 購買商品明細Receipt
    {
        public int 購買商品明細編號Receipt_ID { get; set; }
        public int 訂單編號Order_ID { get; set; }
        public int 商品編號Product_ID { get; set; }
        public int 商品數量Qty { get; set; }
    
        public virtual 訂單總表Orders 訂單總表Orders { get; set; }
        public virtual 商品資料Products 商品資料Products { get; set; }
    }
}
