//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 電影Movies()
        {
            this.我的片單MyMovieLists = new HashSet<我的片單MyMovieLists>();
            this.電影片種MovieType = new HashSet<電影片種MovieType>();
            this.電影主演Cast = new HashSet<電影主演Cast>();
            this.電影代碼MovieCode = new HashSet<電影代碼MovieCode>();
            this.電影產地MovieOrigin = new HashSet<電影產地MovieOrigin>();
            this.電影評論MovieComment = new HashSet<電影評論MovieComment>();
            this.電影圖片MovieIImagesList = new HashSet<電影圖片MovieIImagesList>();
            this.電影導演MovieDirector = new HashSet<電影導演MovieDirector>();
        }
    
        public int 電影編號Movie_ID { get; set; }
        public Nullable<int> 系列編號Series_ID { get; set; }
        public string 中文標題Title_Cht { get; set; }
        public string 英文標題Title_Eng { get; set; }
        public int 上映年份Release_Year { get; set; }
        public Nullable<System.DateTime> 上映日期Release_Date { get; set; }
        public int 片長Runtime { get; set; }
        public int 電影分級編號Rating_ID { get; set; }
        public Nullable<decimal> 評分Rate { get; set; }
        public Nullable<decimal> 期待度anticipation { get; set; }
        public string 票房BoxOffice { get; set; }
        public string 劇情大綱Plot { get; set; }
        public Nullable<System.DateTime> 最後上映日期Released_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<我的片單MyMovieLists> 我的片單MyMovieLists { get; set; }
        public virtual 系列電影MovieSeries 系列電影MovieSeries { get; set; }
        public virtual 電影分級MovieRating 電影分級MovieRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影片種MovieType> 電影片種MovieType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影主演Cast> 電影主演Cast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影代碼MovieCode> 電影代碼MovieCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影產地MovieOrigin> 電影產地MovieOrigin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影評論MovieComment> 電影評論MovieComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影圖片MovieIImagesList> 電影圖片MovieIImagesList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影導演MovieDirector> 電影導演MovieDirector { get; set; }
    }
}
