//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影代碼MovieCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 電影代碼MovieCode()
        {
            this.場次Screening = new HashSet<場次Screening>();
        }
    
        public int 電影代碼編號MovieCode_ID_int { get; set; }
        public int 電影編號Movie_ID { get; set; }
        public int 語言編號Language_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<場次Screening> 場次Screening { get; set; }
        public virtual 電影Movies 電影Movies { get; set; }
        public virtual 電影語言MovieLanguage 電影語言MovieLanguage { get; set; }
    }
}
