//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影院Theater
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 電影院Theater()
        {
            this.商品資料Products = new HashSet<商品資料Products>();
            this.影廳Cinema = new HashSet<影廳Cinema>();
        }
    
        public int 電影院編號Theater_ID { get; set; }
        public string 電影院名稱Theater_Name { get; set; }
        public int 影城編號MainTheater_ID { get; set; }
        public string 營業時間BusinessHours { get; set; }
        public string 電話Phone { get; set; }
        public string 地址Address { get; set; }
        public string 官方網站URL { get; set; }
        public byte[] 電影院照片Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<商品資料Products> 商品資料Products { get; set; }
        public virtual 影城MainTheater 影城MainTheater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<影廳Cinema> 影廳Cinema { get; set; }
    }
}
