//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影評論MovieComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 電影評論MovieComment()
        {
            this.回覆樓數Floor = new HashSet<回覆樓數Floor>();
            this.我的追蹤清單MyFollowLists = new HashSet<我的追蹤清單MyFollowLists>();
            this.評論圖片明細CommentImagesList = new HashSet<評論圖片明細CommentImagesList>();
            this.標籤明細HashtagsList = new HashSet<標籤明細HashtagsList>();
        }
    
        public int 評論編號Comment_ID { get; set; }
        public int 會員編號Member_ID { get; set; }
        public int 電影編號Movie_ID { get; set; }
        public Nullable<decimal> 評分Rate { get; set; }
        public Nullable<decimal> 期待度anticipation { get; set; }
        public string 評論標題Comment_Title { get; set; }
        public string 評論內容Comments { get; set; }
        public System.DateTime 發佈時間Comment_Time { get; set; }
        public Nullable<System.DateTime> 觀影日期Viewing_Time { get; set; }
        public string 觀影方式Source { get; set; }
        public Nullable<int> 公開等級編號Public_ID { get; set; }
        public Nullable<bool> 是否開放討論串OX_Floor { get; set; }
        public int 屏蔽Invisible { get; set; }
        public int 檢舉Report { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<回覆樓數Floor> 回覆樓數Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<我的追蹤清單MyFollowLists> 我的追蹤清單MyFollowLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<評論圖片明細CommentImagesList> 評論圖片明細CommentImagesList { get; set; }
        public virtual 電影Movies 電影Movies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<標籤明細HashtagsList> 標籤明細HashtagsList { get; set; }
    }
}
